// Schéma du formulaire de relevé de bâtiment (valeur assurable / inspection).
// Toutes les sections, champs, options et types de pièces sont définis ici —
// aucune liste de matériaux n'est codée en dur dans les composants.
//
// Règle : on documente (matériaux, quantités, dimensions, présence/absence).
// Aucun champ ne qualifie l'état ou la condition d'une composante.

import type { FormField, FormGroup, FormSection, RoomTypeDef } from "./types";

// ---------------------------------------------------------------------------
// Listes partagées (DRY : réutilisées par la finition intérieure ET le module
// « Relevé par pièce »)
// ---------------------------------------------------------------------------

export const FLOOR_FINISH_OPTIONS = [
  "Aucun",
  "Ardoise",
  "Bois dur",
  "Céramique",
  "Époxy",
  "Linoléum",
  "Marqueterie",
  "Peinture sur dalle béton",
  "Plancher flottant / ingénierie",
  "Prélart",
  "Scellant sur béton",
  "Tapis",
  "Tuiles de vinyle / composite",
  "Tuiles de vinyle",
];

export const CEILING_FINISH_OPTIONS = [
  "Aucun",
  "Contreplaqué",
  "Latte de bois",
  "Placoplâtre",
  "Plafonds suspendus acoustique",
  "Plâtre",
  "Stucco / texturé",
  "Tôle acier émaillé",
  "Tôle acier galvanisé",
  "Tuiles de fibres pressées",
  "Vinyle",
  "Insonorisé",
];

export const WALL_FINISH_OPTIONS = [
  "Aucun",
  "Brique",
  "Brute",
  "Céramique",
  "Contreplaqué",
  "Lambris",
  "Latte de bois",
  "Peinture sur blocs béton",
  "Pierre",
  "Placoplâtre",
  "Préfini",
  "Tôle acier émaillé",
  "Tôle acier galvanisé",
  "Vinyle",
  "Insonorisé",
];

export const BASEMENT_PERIMETER_OPTIONS = [
  "Non fini",
  "Fini à %",
  "Isolé seulement",
  "Isolé et latté",
  "Placoplâtre sans finition",
];

export const RENOVATION_TYPES = [
  "Toiture",
  "Fenêtres",
  "Portes",
  "Revêtements extérieurs",
  "Galeries",
  "Fondations",
  "Sous-sol aménagé",
  "Armoires de cuisine",
  "Recouvrements de planchers",
  "Plomberie",
  "Chauffage",
  "Électricité",
  "Climatisation",
  "Divisions intérieures",
  "Agrandissement",
  "Autre",
];

// ---------------------------------------------------------------------------
// Groupes de navigation (macro-catégories)
// ---------------------------------------------------------------------------

export const GROUPS: FormGroup[] = [
  { id: "dossier", title: "Dossier" },
  { id: "batiment", title: "Bâtiment" },
  { id: "structure", title: "Structure & enveloppe" },
  { id: "interieur", title: "Intérieur" },
  { id: "systemes", title: "Systèmes & équipements" },
  { id: "exterieur", title: "Extérieur" },
  { id: "suivi", title: "Suivi" },
];

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

export const SECTIONS: FormSection[] = [
  // 1 — Dossier -------------------------------------------------------------
  {
    id: "dossier",
    num: 1,
    title: "Dossier",
    short: "Dossier",
    group: "dossier",
    fields: [
      { id: "no_dossier", label: "Numéro de dossier", type: "text", required: true },
      { id: "date_releve", label: "Date", type: "date", required: true },
      { id: "inspecte_par", label: "Inspecté par", type: "text", required: true },
      { id: "personnes_rencontrees", label: "Personnes rencontrées", type: "text" },
      { id: "type_entreprise", label: "Type d'entreprise / propriété", type: "text" },
      { id: "unites_visitees", label: "Unités visitées", type: "text" },
      { id: "notes_generales", label: "Notes générales", type: "textarea" },
    ],
  },

  // 2 — Identification du bâtiment ------------------------------------------
  {
    id: "identification",
    num: 2,
    title: "Identification du bâtiment",
    short: "Identification",
    group: "batiment",
    fields: [
      {
        id: "secteur",
        label: "Secteur",
        type: "radio",
        required: true,
        options: [
          "Résidentiel",
          "Commercial",
          "Industriel",
          "Agricole",
          "Para-industriel",
          "De villégiature",
        ],
        other: true,
      },
      {
        id: "utilisation",
        label: "Utilisation",
        type: "radio",
        required: true,
        options: [
          "Résidentielle",
          "Commerciale",
          "Mixte commerciale et résidentielle",
          "Industrielle",
          "Agricole",
          "Para-industrielle",
          "Institutionnel",
        ],
      },
      {
        id: "types_unites",
        label: "Types d'unités (avec quantités)",
        type: "quantity-list",
        options: ["Studio", "1½", "2½", "3½", "4½", "5½", "6½", "Penthouse"],
        quantityLabel: "Nombre",
      },
      { id: "nb_logements", label: "Nombre de logements", type: "number", min: 0 },
      { id: "nb_condominiums", label: "Nombre de condominiums", type: "number", min: 0 },
      { id: "nb_commerces", label: "Nombre de commerces", type: "number", min: 0 },
      { id: "annee_construction", label: "Année de construction", type: "number", min: 1600, max: 2100 },
      { id: "annee_non_confirmee", label: "Année non confirmée", type: "yesno" },
      { id: "important", label: "Important", type: "yesno" },
    ],
  },

  // 3 — Site, accès & conformité ---------------------------------------------
  {
    id: "site",
    num: 3,
    title: "Site, accès & conformité",
    short: "Site & conformité",
    group: "batiment",
    fields: [
      {
        id: "dist_borne_fontaine",
        label: "Distance borne-fontaine",
        type: "measure",
        units: ["pi", "m", "km"],
        withReference: true,
      },
      {
        id: "dist_caserne",
        label: "Distance caserne de pompiers",
        type: "measure",
        units: ["pi", "m", "km"],
        withReference: true,
      },
      {
        id: "dist_point_eau",
        label: "Distance point d'eau",
        type: "measure",
        units: ["pi", "m", "km"],
        withReference: true,
      },
      {
        id: "accessibilite",
        label: "Accessibilité (logistique d'accès au site)",
        type: "radio",
        options: ["Facile", "Moyenne", "Difficile"],
        other: true,
        help: "Logistique d'accès seulement — pas une évaluation d'état.",
      },
      { id: "plans_architecte", label: "Accès plans architecte", type: "yesno" },
      {
        id: "plans_architecte_nom",
        label: "Nom de l'architecte",
        type: "text",
        showIf: { field: "plans_architecte", equals: "oui" },
      },
      { id: "plans_ingenieur", label: "Accès plans ingénieur", type: "yesno" },
      {
        id: "plans_ingenieur_nom",
        label: "Nom de l'ingénieur",
        type: "text",
        showIf: { field: "plans_ingenieur", equals: "oui" },
      },
      { id: "plans_evacuation", label: "Accès plans d'évacuation", type: "yesno" },
      { id: "avis_non_conformite", label: "Avis de non-conformité", type: "yesno" },
      {
        id: "avis_non_conformite_batiment",
        label: "Avis de non-conformité — bâtiment",
        type: "text",
        showIf: { field: "avis_non_conformite", equals: "oui" },
      },
      {
        id: "avis_non_conformite_reference",
        label: "Avis de non-conformité — référence",
        type: "text",
        showIf: { field: "avis_non_conformite", equals: "oui" },
      },
      { id: "ordonnance_decontamination", label: "Ordonnance de décontamination", type: "yesno" },
      {
        id: "ordonnance_batiment",
        label: "Ordonnance — bâtiment",
        type: "text",
        showIf: { field: "ordonnance_decontamination", equals: "oui" },
      },
      {
        id: "ordonnance_reference",
        label: "Ordonnance — référence",
        type: "text",
        showIf: { field: "ordonnance_decontamination", equals: "oui" },
      },
      {
        id: "fiche_reference",
        label: "Consultation de la fiche de référence",
        type: "yesno",
        help: "Si oui : en demander copie ou photo.",
      },
    ],
  },

  // 4 — Dimensions & superficies ---------------------------------------------
  {
    id: "dimensions",
    num: 4,
    title: "Dimensions & superficies",
    short: "Dimensions",
    group: "batiment",
    special: "floors",
    fields: [
      { id: "nb_etages", label: "Nombre d'étages", type: "number", min: 0 },
      { id: "largeur_batiment", label: "Largeur", type: "number", unit: "pi", min: 0 },
      { id: "profondeur_batiment", label: "Profondeur", type: "number", unit: "pi", min: 0 },
      { id: "dimensions_irregulieres", label: "Dimensions irrégulières / voir croquis", type: "yesno" },
      { id: "aire_bureau", label: "Industriel — aire bureau", type: "number", unit: "pi²", min: 0 },
      {
        id: "aire_totale_batiment_industriel",
        label: "Industriel — aire totale bâtiment",
        type: "number",
        unit: "pi²",
        min: 0,
      },
    ],
  },

  // 5 — Fondations & infrastructure -------------------------------------------
  {
    id: "fondations",
    num: 5,
    title: "Fondations & infrastructure",
    short: "Fondations",
    group: "structure",
    fields: [
      {
        id: "excavation",
        label: "Excavation / préparation du site",
        type: "checkbox-group",
        options: ["En masse dans le sol", "En tranchée dans le sol", "Aucune", "Nivellement seulement"],
      },
      {
        id: "assises",
        label: "Assises / footing",
        type: "checkbox-group",
        options: ["Béton armé", "Pierre sèche", "Bois traité", "Aucune"],
      },
      {
        id: "fondations",
        label: "Fondations",
        type: "checkbox-group",
        options: [
          "Béton coulé",
          "Béton armé",
          "Blocs de béton",
          "Pierres et mortiers",
          "Imperméabilisant",
          "Isolation par extérieur",
          "Piliers excavés",
          "Techno-pieux",
          "Pieux d'enfoncement",
          "Colonnes stationnement souterrain",
        ],
      },
      { id: "fondations_notes", label: "Notes — fondations", type: "textarea" },
    ],
  },

  // 6 — Superstructure ---------------------------------------------------------
  {
    id: "superstructure",
    num: 6,
    title: "Superstructure",
    short: "Superstructure",
    group: "structure",
    fields: [
      {
        id: "structure_batiment",
        label: "Structure du bâtiment (%)",
        type: "percentage-group",
        options: [
          "Bois",
          "Bois post & beam",
          "Mill type",
          "Béton",
          "Béton préfabriqué",
          "Blocs de béton",
          "Acier",
          "Acier léger",
          "Acier préfabriqué",
        ],
        help: "La somme des pourcentages ne doit pas dépasser 100 %.",
      },
      {
        id: "murs_exterieurs",
        label: "Murs extérieurs (composition)",
        type: "checkbox-group",
        options: [
          "Montant de bois",
          "Bois post & beam",
          "Pièce sur pièce",
          "Béton",
          "Béton préfabriqué",
          "Blocs de béton",
          "Montant métallique",
          "Acier léger",
          "Acier préfabriqué",
        ],
      },
      {
        id: "murs_mitoyens",
        label: "Murs mitoyens",
        type: "checkbox-group",
        options: ["Bois", "Béton", "Blocs de béton", "Maçonnerie", "Aucun"],
      },
      {
        id: "isolation",
        label: "Isolation",
        type: "radio",
        options: ["Présumé standard", "Aucune", "Novoclimat"],
        other: true,
      },
      { id: "toiture_pente_pct", label: "Toiture en pente (%)", type: "number", unit: "%", min: 0, max: 100 },
      {
        id: "toiture_pente_ratio",
        label: "Pente (x/12)",
        type: "number",
        unit: "/12",
        min: 0,
        showIf: { field: "toiture_pente_pct", truthy: true },
      },
      { id: "toiture_plate_pct", label: "Toiture plate (%)", type: "number", unit: "%", min: 0, max: 100 },
      {
        id: "toiture_structure",
        label: "Toiture — structure",
        type: "checkbox-group",
        options: [
          "Fermes préfabriquées en bois",
          "Structure de bois",
          "Structure d'acier",
          "Structure béton",
          "Structure acier avec dalle béton",
        ],
      },
    ],
    matrices: [
      {
        id: "composition_planchers",
        title: "Composition des planchers (par étage, %)",
        validateSum: true,
        other: true,
        options: [
          "Asphalte",
          "Béton sur pontage de bois mou",
          "Dalle de béton sur le sol isolé ou non",
          "Dalle de béton en radier",
          "Dalle de béton sur pontage d'acier",
          "Dalle structurale",
          "Faux plancher",
          "Gravier concassé",
          "Mill-type",
          "Pontage de bois mou sur ossature de bois mou",
          "Pontage de bois mou sur pontage d'acier",
          "Insonorisation",
        ],
      },
    ],
  },

  // 7 — Enveloppe extérieure ---------------------------------------------------
  {
    id: "enveloppe",
    num: 7,
    title: "Enveloppe extérieure",
    short: "Enveloppe",
    group: "structure",
    matrices: [
      {
        id: "revetement_murs",
        title: "Revêtement des murs (par étage / zone, %)",
        validateSum: true,
        other: true,
        options: [
          "Acrylique sur béton",
          "Acrylique sur isolation",
          "Agrégat",
          "Bloc de béton à face éclatée",
          "Brique",
          "Brique autoportante / Novabrick",
          "Canexel / Smart / Goodfellow",
          "Déclin aluminium",
          "Déclin bois mou",
          "Déclin fibres pressées",
          "Déclin fibrociment",
          "Déclin vinyle",
          "Parement copolymère",
          "Peinture sur",
          "Pierre de",
          "Tôle acier émaillé",
          "Tôle acier galvanisé",
          "Bloc architectural",
        ],
      },
    ],
    fields: [
      {
        id: "revetement_toiture",
        label: "Revêtement de toiture",
        type: "checkbox-group",
        other: true,
        options: [
          "Acier",
          "Ardoise",
          "Bardeaux d'asphalte",
          "Bardeaux de cèdre",
          "Béton",
          "Cuivre",
          "Fibre de verre",
          "Goudron et gravier",
          "Membrane élastomère",
          "Toiture permanente",
          "Papier d'asphalte",
          "Tôle à baguette",
          "Tôle canadienne",
          "Tôle acier émaillé",
          "Tôle acier galvanisé",
          "Tuiles de plastique",
          "Toiture inversée",
        ],
      },
      {
        id: "fenetres",
        label: "Fenêtres",
        type: "checkbox-group",
        other: true,
        options: ["Acier", "Aluminium", "PVC", "Bois", "Hybride", "Volet", "Grillage de sécurité"],
      },
      {
        id: "fenetres_hybride_precision",
        label: "Fenêtres hybrides — précision",
        type: "text",
        showIf: { field: "fenetres", includes: "Hybride" },
      },
      {
        id: "portes_pietonnes",
        label: "Portes piétonnes",
        type: "checkbox-group",
        other: true,
        options: ["Acier", "Aluminium", "Verre thermos patio", "Bois"],
      },
      {
        id: "portes_garage",
        label: "Portes de garage",
        type: "checkbox-group",
        other: true,
        options: ["Bois", "Aluminium", "Ouvre-porte automatique", "Acier"],
      },
      {
        id: "portes_coulissantes",
        label: "Portes coulissantes",
        type: "checkbox-group",
        other: true,
        options: ["Bois", "Aluminium", "PVC", "Toiles", "Transparente", "À rouleaux"],
      },
    ],
  },

  // 8 — Finition intérieure ------------------------------------------------------
  {
    id: "finition_interieure",
    num: 8,
    title: "Finition intérieure (par étage)",
    short: "Finition int.",
    group: "interieur",
    matrices: [
      {
        id: "finition_planchers",
        title: "Finition des planchers (par étage, %)",
        validateSum: true,
        other: true,
        options: FLOOR_FINISH_OPTIONS,
      },
      {
        id: "finition_plafonds",
        title: "Finition du plafond (par étage, %)",
        validateSum: true,
        other: true,
        options: CEILING_FINISH_OPTIONS,
      },
      {
        id: "finition_murs",
        title: "Finition des murs et divisions (par étage, %)",
        validateSum: true,
        other: true,
        options: WALL_FINISH_OPTIONS,
      },
    ],
    fields: [
      {
        id: "sous_sol_pourtour",
        label: "Sous-sol — pourtour mur de fondation",
        type: "radio",
        options: BASEMENT_PERIMETER_OPTIONS,
      },
      {
        id: "sous_sol_pourtour_pct",
        label: "Fini à (%)",
        type: "number",
        unit: "%",
        min: 0,
        max: 100,
        showIf: { field: "sous_sol_pourtour", equals: "Fini à %" },
      },
      {
        id: "composition_divisions",
        label: "Composition des divisions",
        type: "checkbox-group",
        other: true,
        options: ["Colombage bois", "Colombage métallique", "Blocs béton", "Béton", "Blocs de verre", "Vitrine"],
      },
      { id: "finition_notes", label: "Notes — finition intérieure", type: "textarea" },
    ],
  },

  // 9 — Relevé par pièce -----------------------------------------------------------
  {
    id: "pieces",
    num: 9,
    title: "Relevé par pièce",
    short: "Pièces",
    group: "interieur",
    special: "rooms",
  },

  // 10 — Mécanique, électricité & plomberie -----------------------------------------
  {
    id: "mecanique",
    num: 10,
    title: "Mécanique, électricité & plomberie",
    short: "Méc. / élec. / plomb.",
    group: "systemes",
    fields: [
      { id: "interrupteur_principal", label: "Interrupteur principal", type: "checkbox" },
      {
        id: "amperage",
        label: "Ampérage",
        type: "select",
        options: ["100", "125", "200", "400", "600"],
        other: true,
        unit: "A",
      },
      { id: "voltage", label: "Voltage", type: "text", unit: "V" },
      {
        id: "electricite_options",
        label: "Électricité",
        type: "checkbox-group",
        options: [
          "Fusibles",
          "Disjoncteurs",
          "Relié au bâtiment principal",
          "Éclairage LED",
          "Fluorescents",
          "Transformateur",
          "Câblage souterrain",
          "Inverseur automatique pour génératrice",
        ],
      },
      {
        id: "chauffage",
        label: "Chauffage (indiquer les étages desservis en note)",
        type: "quantity-list",
        withNote: true,
        quantityLabel: "Nb / %",
        options: [
          "Aérotherme vapeur",
          "Aérotherme gaz naturel",
          "Aérotherme propane",
          "Aérotherme électrique",
          "Air chaud alimenté par",
          "Ventilo-convecteur",
          "Géothermie (profondeur du puits en note)",
          "Plinthe eau chaude alimentée par",
          "Plinthes électriques",
          "Radiant eau chaude alimenté par",
          "Radiant électrique",
          "Radiant suspendu",
          "Solaire",
          "Thermopompe chauffage seulement",
          "Thermopompe murale chauffage/climatisation",
          "Unité refroidissement/chauffage combinés",
          "Aucun",
        ],
      },
      {
        id: "climatisation",
        label: "Climatisation",
        type: "quantity-list",
        options: [
          "Air climatisé fenêtre",
          "Thermopompe climatisation seulement",
          "Unité de climatisation centrale",
          "Unité murale",
        ],
      },
      {
        id: "ventilation",
        label: "Ventilation",
        type: "quantity-list",
        options: [
          "Échangeur d'air",
          "Récupérateur de chaleur",
          "Système de déshumidification",
          "Trappe de ventilation",
          "Ventilateurs de plafond",
          "Ventilateurs d'évacuation",
          "Humidification",
        ],
      },
      {
        id: "plomberie",
        label: "Plomberie (quantités)",
        type: "quantity-list",
        other: true,
        options: [
          "Abreuvoir",
          "Bain thérapeutique",
          "Bain tourbillon",
          "Bain",
          "Bain-douche",
          "Bidet",
          "Chauffe-eau",
          "Chauffe-eau 40 gallons",
          "Chauffe-eau 60 gallons",
          "Cuve de lavage",
          "Douche oculaire",
          "Douche vapeur",
          "Douche",
          "Évier de cuisine",
          "Fontaine",
          "Lavabo",
          "Lavabo sur pied",
          "Lavabo mural",
          "Sauna",
          "Sortie boyau d'arrosage",
          "Sortie laveuse-sécheuse",
          "Spa intérieur",
          "Toilette",
          "Tuyauterie seulement",
          "Urinoir",
        ],
      },
      {
        id: "gicleurs",
        label: "Gicleurs",
        type: "checkbox-group",
        options: ["Gicleurs air", "Gicleurs eau"],
      },
      { id: "gicleurs_notes", label: "Notes — gicleurs", type: "textarea" },
    ],
  },

  // 11 — Équipements & protection incendie ---------------------------------------------
  {
    id: "equipements",
    num: 11,
    title: "Équipements & protection incendie",
    short: "Équipements",
    group: "systemes",
    fields: [
      {
        id: "encastrements",
        label: "Encastrements / équipements",
        type: "quantity-list",
        withNote: true,
        options: [
          "Adoucisseur d'eau",
          "Armoires de cuisine en mélamine",
          "Ascenseur (capacité en note)",
          "Câble hydraulique (nb d'arrêts)",
          "Aspirateur central",
          "Bar (longueur en note)",
          "Boiseries",
          "Broyeur",
          "Câblage informatique",
          "Câblage téléphonique",
          "Casiers postaux",
          "Cheminée brique",
          "Cheminée métal",
          "Cheminée métal recouverte",
          "Cheminée pierre",
          "Cheminée blocs béton",
          "Chute à déchet",
          "Colonnes décoratives",
          "Comptoir",
          "Comptoir stratifié",
          "Cuisinière encastrée",
          "Escalier métal",
          "Escalier bois dur",
          "Four encastré",
          "Foyer bois",
          "Foyer gaz naturel",
          "Foyer propane",
          "Garde-robe de cèdre",
          "Gorges",
          "Hotte suspendue (longueur en note)",
          "Îlot central",
          "Lave-vaisselle encastré",
          "Meubles encastrés",
          "Mezzanine",
          "Moulures",
          "Plaque de cuisson",
          "Poêle à bois",
          "Poêle à combustion lente",
          "Porte de voûte",
          "Portes françaises",
          "Portes intérieures embossées",
          "Portes-miroirs",
          "Puits de lumière",
          "Système d'alarme intrusion/feu",
          "Relié à centrale",
          "Détecteurs mouvement",
          "Caméras/moniteurs",
          "Système de son encastré",
          "Système de traitement d'eau",
          "Toit cathédrale",
          "Vanité salle de bain",
          "Système intercom",
          "Contrôle d'accès",
        ],
      },
      {
        id: "equipements_industriels",
        label: "Équipements fixes / industriels",
        type: "quantity-list",
        withNote: true,
        options: [
          "Chambre à peinture",
          "Chambre froide",
          "Chambre réfrigérée",
          "Compacteur à déchet",
          "Compresseur",
          "Congélateur/chambre réfrigérée",
          "Dévidoir d'huile",
          "Élévateur d'auto",
          "Élévateur hydraulique",
          "Génératrice",
          "Ligne à air",
          "Pont roulant (longueur, largeur, capacité en note)",
          "Potence (portée en note)",
        ],
      },
      {
        id: "protection_incendie",
        label: "Protection incendie",
        type: "quantity-list",
        options: [
          "Cabinet avec boyau d'arrosage",
          "Déclencheur manuel",
          "Détecteur de chaleur",
          "Détecteurs de fumée",
          "Extincteurs",
          "Lumières d'urgence",
          "Porte coupe-feu",
          "Sirène",
          "Sortie d'urgence",
          "Système d'alarme incendie",
          "Détecteur de monoxyde de carbone",
        ],
      },
    ],
  },

  // 12 — Extérieur & aménagements ---------------------------------------------------------
  {
    id: "exterieur",
    num: 12,
    title: "Extérieur & aménagements",
    short: "Extérieur",
    group: "exterieur",
    fields: [
      {
        id: "divers_exterieur",
        label: "Divers extérieur",
        type: "quantity-list",
        withNote: true,
        options: [
          "Abri d'auto",
          "Auvent (grandeur en note)",
          "Balcon en",
          "Balustrades",
          "Barrières anti-chute glace/neige",
          "BBQ encastré",
          "Borne de protection",
          "Colonnes décoratives",
          "Cloche",
          "Clocher (hauteur en note)",
          "Dalle béton sur sol (dimensions en note)",
          "Échelle extérieure (hauteur en note)",
          "Échelle extérieure avec crinoline",
          "Enseigne murale (dimensions en note)",
          "Entrée cave",
          "Escalier extérieur en",
          "Galerie en",
          "Gargouilles",
          "Garde-corps en",
          "Gazebo",
          "Girouettes",
          "Gouttières et descentes (longueur en note)",
          "Horloge (grandeur en note)",
          "Lettrage (hauteur en note)",
          "Lucarnes",
          "Marquise",
          "Ornementation",
          "Patios en",
          "Perrons de béton",
          "Quais de chargement",
          "Rampes handicapées",
          "Remises annexées",
          "Sentinelles",
          "Tableaux lumineux (dimensions en note)",
          "Terrasses en",
          "Toits de galerie",
          "Verrière",
        ],
      },
      {
        id: "amenagements",
        label: "Aménagements (longueur / largeur / aire)",
        type: "dims-list",
        options: ["Gazon", "Système d'arrosage", "Asphalte", "Concassé", "Béton", "Pavé interbloc", "Trottoir en"],
      },
      {
        id: "vegetation",
        label: "Végétation (quantité / longueur / hauteur en note)",
        type: "quantity-list",
        withNote: true,
        options: ["Arbres", "Haie"],
      },
      { id: "services_municipaux", label: "Services municipaux", type: "yesno" },
      { id: "puits", label: "Puits", type: "checkbox" },
      {
        id: "fosse_septique",
        label: "Fosse septique",
        type: "radio",
        options: ["Standard", "Bio-tourbe", "Roseau"],
        other: true,
      },
      { id: "champ_epuration", label: "Champ d'épuration", type: "checkbox" },
      { id: "enseigne_sur_pied", label: "Enseigne sur pied", type: "checkbox" },
      {
        id: "enseigne_grandeur",
        label: "Enseigne — grandeur",
        type: "text",
        showIf: { field: "enseigne_sur_pied", equals: true },
      },
      {
        id: "enseigne_hauteur_poteau",
        label: "Enseigne — hauteur du poteau",
        type: "text",
        showIf: { field: "enseigne_sur_pied", equals: true },
      },
      { id: "lampadaires_quantite", label: "Lampadaires — quantité", type: "number", min: 0 },
      {
        id: "lampadaires_hauteur",
        label: "Lampadaires — hauteur",
        type: "number",
        unit: "pi",
        min: 0,
        showIf: { field: "lampadaires_quantite", truthy: true },
      },
      {
        id: "lampadaires_nb_lumieres",
        label: "Lampadaires — nombre de lumières",
        type: "number",
        min: 0,
        showIf: { field: "lampadaires_quantite", truthy: true },
      },
      { id: "pancarte_contreplaque", label: "Pancarte en contreplaqué", type: "checkbox" },
      { id: "poteaux", label: "Poteaux", type: "checkbox" },

      // Piscine ------------------------------------------------------------
      { id: "piscine", label: "Piscine", type: "yesno" },
      {
        id: "piscine_type",
        label: "Type de piscine",
        type: "radio",
        options: ["Creusée", "Hors-terre"],
        showIf: { field: "piscine", equals: "oui" },
      },
      {
        id: "piscine_parois_creusee",
        label: "Parois (creusée)",
        type: "radio",
        options: ["Acier", "Résine de synthèse", "Béton"],
        other: true,
        showIf: { field: "piscine_type", equals: "Creusée" },
      },
      {
        id: "piscine_parois_horsterre",
        label: "Parois (hors-terre)",
        type: "radio",
        options: ["Acier", "Aluminium/résine"],
        other: true,
        showIf: { field: "piscine_type", equals: "Hors-terre" },
      },
      {
        id: "piscine_forme",
        label: "Forme / dimensions",
        type: "select",
        options: [
          "Ronde 12 pi",
          "Ronde 15 pi",
          "Ronde 18 pi",
          "Ronde 21 pi",
          "Ronde 24 pi",
          "Ronde 27 pi",
          "Ovale 10×22",
          "Ovale 12×24",
          "Ovale 15×30",
          "Ovale 18×33",
        ],
        other: true,
        showIf: { field: "piscine", equals: "oui" },
      },
      {
        id: "piscine_quantite",
        label: "Piscines — quantité",
        type: "number",
        min: 0,
        showIf: { field: "piscine", equals: "oui" },
      },
      {
        id: "piscine_eclairage",
        label: "Piscine — éclairage",
        type: "checkbox",
        showIf: { field: "piscine", equals: "oui" },
      },
      {
        id: "piscine_glissoire",
        label: "Piscine — glissoire",
        type: "checkbox",
        showIf: { field: "piscine", equals: "oui" },
      },
      {
        id: "chauffage_piscine",
        label: "Chauffage piscine",
        type: "checkbox-group",
        options: [
          "Thermopompe 70–85 MBH",
          "Thermopompe 107–140 MBH",
          "Chauffe-eau gaz 125–250 MBH",
          "Chauffe-eau gaz 250–400 MBH",
          "Panneau solaire",
          "Chauffe-eau huile",
          "Chauffe-eau bois",
        ],
        showIf: { field: "piscine", equals: "oui" },
      },

      // SPA ------------------------------------------------------------------
      { id: "spa", label: "SPA", type: "yesno" },
      {
        id: "spa_places",
        label: "SPA — nombre de places",
        type: "number",
        min: 0,
        showIf: { field: "spa", equals: "oui" },
      },
      {
        id: "spa_niveau",
        label: "SPA — niveau (classification du produit)",
        type: "radio",
        options: ["Normal", "Standard", "Supérieur"],
        showIf: { field: "spa", equals: "oui" },
        help: "Classification du produit, pas une évaluation d'état.",
      },

      // Clôture ----------------------------------------------------------------
      {
        id: "cloture_type",
        label: "Clôture — type",
        type: "checkbox-group",
        options: ["Bois", "Mailles de chaîne", "Fer forgé", "PVC"],
        other: true,
      },
      {
        id: "cloture_hauteur",
        label: "Clôture — hauteur",
        type: "select",
        options: ["4 pi", "5 pi", "6 pi"],
        other: true,
        showIf: { field: "cloture_type", truthy: true },
      },
      {
        id: "cloture_longueur",
        label: "Clôture — longueur",
        type: "number",
        unit: "pi",
        min: 0,
        showIf: { field: "cloture_type", truthy: true },
      },

      // Murs de soutènement ------------------------------------------------------
      { id: "soutenement_longueur", label: "Murs de soutènement — longueur", type: "number", unit: "pi", min: 0 },
      { id: "soutenement_largeur", label: "Murs de soutènement — largeur", type: "number", unit: "pi", min: 0 },
      { id: "soutenement_aire", label: "Murs de soutènement — aire", type: "number", unit: "pi²", min: 0 },
      { id: "soutenement_quantite", label: "Murs de soutènement — quantité", type: "number", min: 0 },

      // Foyer extérieur -------------------------------------------------------------
      { id: "foyer_exterieur", label: "Foyer extérieur", type: "yesno" },
      {
        id: "foyer_exterieur_notes",
        label: "Foyer extérieur — notes",
        type: "textarea",
        showIf: { field: "foyer_exterieur", equals: "oui" },
      },
    ],
  },

  // 13 — Rénovations ---------------------------------------------------------------------
  {
    id: "renovations",
    num: 13,
    title: "Rénovations",
    short: "Rénovations",
    group: "suivi",
    special: "renovations",
  },

  // 14 — Résumé & export --------------------------------------------------------------------
  {
    id: "resume",
    num: 14,
    title: "Résumé & export",
    short: "Résumé",
    group: "suivi",
    special: "summary",
  },
];

// ---------------------------------------------------------------------------
// Relevé par pièce : types de pièces et champs spécifiques
// (les revêtements plancher/mur/plafond communs réutilisent les listes de la
// section 8 — voir RoomList)
// ---------------------------------------------------------------------------

export const ROOM_SCHEMAS: RoomTypeDef[] = [
  {
    id: "cuisine",
    label: "Cuisine",
    fields: [
      {
        id: "armoires",
        label: "Armoires",
        type: "checkbox-group",
        options: ["Mélamine", "Bois", "Thermoplastique/polyester"],
        other: true,
      },
      { id: "armoires_lineaire", label: "Armoires — linéaire / quantité", type: "text" },
      {
        id: "comptoir",
        label: "Comptoir",
        type: "checkbox-group",
        options: ["Stratifié", "Quartz", "Granit", "Bois", "Béton"],
        other: true,
      },
      { id: "dosseret", label: "Dosseret", type: "checkbox" },
      { id: "ilot_central", label: "Îlot central", type: "yesno" },
      {
        id: "ilot_dimensions",
        label: "Îlot — dimensions",
        type: "text",
        showIf: { field: "ilot_central", equals: "oui" },
      },
      { id: "evier_type", label: "Évier", type: "radio", options: ["Simple", "Double"] },
      { id: "evier_materiau", label: "Évier — matériau", type: "text" },
      {
        id: "encastres",
        label: "Encastrés",
        type: "quantity-list",
        withNote: true,
        options: [
          "Lave-vaisselle",
          "Four encastré",
          "Plaque de cuisson",
          "Cuisinière encastrée",
          "Hotte (longueur en note)",
          "Micro-ondes encastré",
          "Réfrigérateur encastré",
        ],
      },
      { id: "garde_manger", label: "Garde-manger", type: "checkbox" },
    ],
  },
  {
    id: "salle_bain",
    label: "Salle de bain",
    fields: [
      {
        id: "type_sdb",
        label: "Type",
        type: "radio",
        options: ["Complète", "Salle d'eau", "Principale", "Ensuite"],
      },
      {
        id: "bain",
        label: "Bain",
        type: "checkbox-group",
        options: ["Standard", "Podium", "Autoportant", "Tourbillon", "Thérapeutique"],
        other: true,
      },
      {
        id: "douche",
        label: "Douche",
        type: "checkbox-group",
        options: ["Standard", "Céramique", "Vapeur", "Verre"],
      },
      { id: "toilette_quantite", label: "Toilettes — quantité", type: "number", min: 0 },
      { id: "vanite_quantite", label: "Vanités — quantité", type: "number", min: 0 },
      { id: "vanite_longueur", label: "Vanités — longueur", type: "text" },
      {
        id: "lavabo",
        label: "Lavabo",
        type: "checkbox-group",
        options: ["Sur pied", "Mural", "Encastré", "Vasque"],
      },
      { id: "bidet", label: "Bidet", type: "checkbox" },
      { id: "plancher_chauffant", label: "Plancher chauffant", type: "yesno" },
      { id: "ventilateur_evacuation", label: "Ventilateur d'évacuation", type: "checkbox" },
    ],
  },
  {
    id: "chambre",
    label: "Chambre",
    fields: [
      {
        id: "garde_robe",
        label: "Garde-robe",
        type: "checkbox-group",
        options: ["Standard", "Walk-in", "Cèdre"],
      },
      { id: "nb_placards", label: "Nombre de placards", type: "number", min: 0 },
    ],
  },
  {
    id: "salon",
    label: "Salon / séjour",
    fields: [
      {
        id: "foyer",
        label: "Foyer",
        type: "checkbox-group",
        options: ["Bois", "Gaz naturel", "Propane", "Électrique", "Encastré"],
      },
      { id: "toit_cathedrale", label: "Toit cathédrale", type: "yesno" },
      { id: "boiseries_moulures", label: "Boiseries / moulures", type: "checkbox" },
    ],
  },
  {
    id: "salle_a_manger",
    label: "Salle à manger",
    fields: [
      { id: "boiseries", label: "Boiseries", type: "checkbox" },
      { id: "moulures", label: "Moulures", type: "checkbox" },
      { id: "colonnes_decoratives", label: "Colonnes décoratives", type: "checkbox" },
    ],
  },
  {
    id: "salle_familiale",
    label: "Salle familiale",
    fields: [
      {
        id: "foyer_poele",
        label: "Foyer / poêle",
        type: "checkbox-group",
        options: ["Foyer bois", "Foyer gaz naturel", "Foyer propane", "Foyer électrique", "Poêle à bois", "Poêle à combustion lente"],
      },
      { id: "bar", label: "Bar", type: "yesno" },
      {
        id: "bar_longueur",
        label: "Bar — longueur",
        type: "text",
        showIf: { field: "bar", equals: "oui" },
      },
      { id: "systeme_son_encastre", label: "Système de son encastré", type: "checkbox" },
    ],
  },
  {
    id: "sous_sol",
    label: "Sous-sol (aménagé)",
    fields: [
      {
        id: "niveau_finition",
        label: "Niveau de finition",
        type: "radio",
        options: BASEMENT_PERIMETER_OPTIONS,
      },
      {
        id: "niveau_finition_pct",
        label: "Fini à (%)",
        type: "number",
        unit: "%",
        min: 0,
        max: 100,
        showIf: { field: "niveau_finition", equals: "Fini à %" },
      },
      {
        id: "foyer_poele_ss",
        label: "Foyer / poêle",
        type: "checkbox-group",
        options: ["Foyer", "Poêle à bois", "Poêle à combustion lente"],
      },
      { id: "entree_cave", label: "Entrée cave", type: "checkbox" },
    ],
  },
  {
    id: "buanderie",
    label: "Buanderie / salle de lavage",
    fields: [
      { id: "sortie_laveuse_secheuse", label: "Sortie laveuse-sécheuse", type: "checkbox" },
      { id: "cuve_lavage", label: "Cuve de lavage", type: "checkbox" },
      { id: "chauffe_eau_present", label: "Chauffe-eau présent", type: "yesno" },
      {
        id: "chauffe_eau_capacite",
        label: "Chauffe-eau — capacité",
        type: "text",
        placeholder: "ex. 40 gallons",
        showIf: { field: "chauffe_eau_present", equals: "oui" },
      },
    ],
  },
  {
    id: "bureau",
    label: "Bureau / espace de travail",
    fields: [
      { id: "cablage_informatique", label: "Câblage informatique", type: "checkbox" },
      { id: "cablage_telephonique", label: "Câblage téléphonique", type: "checkbox" },
    ],
  },
  {
    id: "vestibule",
    label: "Vestibule / hall / corridor / rangement",
    fields: [
      { id: "garde_robe_cedre", label: "Garde-robe de cèdre", type: "checkbox" },
      { id: "casiers_postaux", label: "Casiers postaux — nombre", type: "number", min: 0 },
    ],
  },
  {
    id: "autre",
    label: "Autre",
    fields: [],
  },
];

export function getRoomSchema(typeId: string): RoomTypeDef | undefined {
  return ROOM_SCHEMAS.find((r) => r.id === typeId);
}

export function getSection(id: string): FormSection | undefined {
  return SECTIONS.find((s) => s.id === id);
}

export function sectionsOfGroup(groupId: string): FormSection[] {
  return SECTIONS.filter((s) => s.group === groupId);
}

/** valeur « Autre » utilisée dans les groupes d'options */
export const OTHER_OPTION = "Autre";
